In [3]:
class Employee:
    no_of_employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.no_of_employees += 1

    @staticmethod
    def average_salary(femployees, n):
        add = 0
        for employee in femployees:
            add += employee.salary
        return add / n


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

def main():
    femployees = []
    employees = []
    femp1 = FulltimeEmployee("Kiran", "Kumar", 145000, "Team Lead")
    femployees.append(femp1)
    femp2 = FulltimeEmployee("Manideep", "Reddy", 180000, "Delivery Manager")
    femployees.append(femp2)
    femp3 = FulltimeEmployee("Sushma", "Shetty", 155000, "Project Lead")
    femployees.append(femp3)
    femp4 = FulltimeEmployee("Vaishnavi", "Reddy", 180000, "hr")
    femployees.append(femp4)
    employee1 = Employee("Mahitha", "Reddy", 96000, "Developer")
    employees.append(employee1)
    employee2 = Employee("Bharat", "Kumar", 50000, "Tester")
    employees.append(employee2)
    print("Average salary of fulltimeemployees:", FulltimeEmployee.average_salary(femployees, (len(femployees))))
    print("Average salary of employees:", Employee.average_salary(employees, (len(employees))))

if __name__ == "__main__":
    main()

Average salary of fulltimeemployees: 165000.0
Average salary of employees: 73000.0


In [4]:
class Employee:
    no_of_employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.no_of_employees += 1

    @staticmethod
    def average_salary(femployees, n):
        add = 0
        for employee in femployees:
            add += employee.salary
        return add / n


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

def main():
    femployees = []
    employees = []
    femp1 = FulltimeEmployee("Kiran", "Kumar", 145000, "Team Lead")
    femployees.append(femp1)
    femp2 = FulltimeEmployee("Manideep", "Reddy", 180000, "Delivery Manager")
    femployees.append(femp2)
    femp3 = FulltimeEmployee("Sushma", "Shetty", 155000, "Project Lead")
    femployees.append(femp3)
    femp4 = FulltimeEmployee("Vaishnavi", "Reddy", 180000, "hr")
    femployees.append(femp4)
    employee1 = Employee("Mahitha", "Reddy", 96000, "Developer")
    employees.append(employee1)
    employee2 = Employee("Bharat", "Kumar", 50000, "Tester")
    employees.append(employee2)
    print("Average salary of fulltimeemployees:", FulltimeEmployee.average_salary(femployees, (len(femployees))))
    print("Average salary of employees:", Employee.average_salary(employees, (len(employees))))

if __name__ == "__main__":
    main()

Average salary of fulltimeemployees: 165000.0
Average salary of employees: 73000.0


In [5]:
import numpy as np
z = np.random.uniform(1, 20, 20)
m = z.reshape(4, 5)
print(m)

m = np.where(m == np.max(m, axis=1, keepdims=True), 0, m)
print(m)


[[15.95386355  3.44342758 14.01136201  7.33465021 14.73015806]
 [13.00611984  1.55381051 17.4117452   8.42964631 11.47316555]
 [ 5.14200628 11.28301668 15.45666762 12.64556865  5.42561603]
 [10.04394295 12.22636677 15.42041354  9.6046746  17.74351   ]]
[[ 0.          3.44342758 14.01136201  7.33465021 14.73015806]
 [13.00611984  1.55381051  0.          8.42964631 11.47316555]
 [ 5.14200628 11.28301668  0.         12.64556865  5.42561603]
 [10.04394295 12.22636677 15.42041354  9.6046746   0.        ]]
